### PR TITLE
Yoonsele

### PR DESCRIPTION
**Pull request by christie26**
1. Remove emit for test and use `setTimeout` instead in `app.test.ts`.
After the change, there is error when I run with `--detectOpenHandles` flag. -> let's check together

2. Make sure test `Board-applyPenalty-distance-Equal-to-line` works well. I changed fixedTiles to make good distance.

### CODE REVIEW

**Comment by balkisous** [comment]
You fix the test of board but only if we run the test alone (Board-applyPenalty-distance-Equal-to-line) i check with console.log line and distance are equal 
but if we run it with others he didnt test the line "else if (line == distance) {" because i check with the console.log and distance and line are no more equal 

So i find a way to make it works add this test 
```
test("Board-applyPenalty-distance-Equal-to-line", () => {
    const fixPieceIfTouchSpy = jest.spyOn(Board.prototype, "fixPieceIfTouch");
    const fixPieceToBoardSpy = jest.spyOn(Board.prototype, "fixPieceToBoard");
    for (let stop = 0; stop < 10; stop++) {
      board.fixedTiles[stop] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    }
    for (let stop = 10; stop < 19; stop++) {
      board.fixedTiles[stop] = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
    }

    board.recievePenalty(8);
    board.applyPenalty();

    expect(fixPieceIfTouchSpy).toHaveBeenCalled();
    expect(fixPieceToBoardSpy).toHaveBeenCalled();
  });
  ```
at the second test place of Board.test and line 293-294 will be done and tested
I add this line in your test function 
```
    for (let stop = 0; stop < 10; stop++) {
      board.fixedTiles[stop] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    }
```
I let you add it in your code because you're branch is not upadate with master and I wouldn't push in your branch because i you didn't pull and push maybe there will be some merge conflict

**Comment by balkisous** [comment]
and for the setTimeout in the app test file, it work's for all test except "App-Keboard-event-sprint-space" and "App-Keboard-event-arrow-down" its the same problem as when we did it with additional socket.emit and i don't know how to fix, 
I will try but know that I already try to fix when it was the socket.emit way

**Comment by balkisous** [comment]
Screenshot 2024-11-20 at 17 33 37

Here what we have when you fix board test (with the first i wrote) and with commented the two tests of app who gives leak, I think we can try to fix the tests of app but if we didn't succeed we can also push it like this

**Comment by christie26** [comment]
I read your comment and try to add your lines but it still doesn't cover the case of (line == distance). I think currentPiece of board is not properly set.

**Comment by balkisous** [comment]
You have to put the test on the second place of all the tests just after testing constructor test

**Pull request merged**
